### PR TITLE
fix: check for binding in Metadata01Test

### LINKED ISSUE #197: Metadata01Test missing required "binding" attribute
# Bug Report

## Describe the Bug

As per the DSP [2025-01](https://eclipse-dataspace-protocol-base.github.io/DataspaceProtocol/2025-1-RC4/#exposure-of-dataspace-protocol-versions), the attribute "binding" is required as part of the `protocolVersion` response given by a participant.

Metadata01Test only checks if `version` is "2025-1" and `path` is present.

### PR DESCRIPTION
**Pull request by rafaelmag110**
## What this PR changes/adds

Adds an assertion to check if the attribute "binding" is part of Version object.

## Why it does that

Compliance with DSP 2025-1.

## Linked Issue(s)

Closes #197

### CODE REVIEW

**Review by jimmarino — APPROVED** [review]
Thanks!

File: dsp/dsp-metadata/src/main/java/org/eclipse/dataspacetck/dsp/verification/metadata/Metadata01Test.java [hunk 1]
```diff
@@ -56,6 +56,7 @@ public void cat_01_01() {
             assertThat(entry.get("version")).isNotNull()
                     .isEqualTo("2025-1");
             assertThat(entry.get("path")).isNotNull();
+            assertThat(entry.get("binding")).isNull();
```
Comment (wolf4ood) [inline dsp/dsp-metadata/src/main/java/org/eclipse/dataspacetck/dsp/verification/metadata/Metadata01Test.java:59]: Isn't this check `isNotNull` since it's a required property?

Comment (rafaelmag110) [reply dsp/dsp-metadata/src/main/java/org/eclipse/dataspacetck/dsp/verification/metadata/Metadata01Test.java:59]: @wolf4ood Of course it should. Damn. Sorry about that.
